import os
import re
import google.generativeai as genai
from pypdf import PdfReader
from fpdf import FPDF
import streamlit as st
from dotenv import load_dotenv

# Load env variables
load_dotenv()

class SignetLogic:
    def __init__(self):
        self.api_key = self._get_api_key()
        if self.api_key:
            genai.configure(api_key=self.api_key)

    def _get_api_key(self):
        if "GOOGLE_API_KEY" in st.secrets:
            return st.secrets["GOOGLE_API_KEY"]
        elif os.getenv("GOOGLE_API_KEY"):
            return os.getenv("GOOGLE_API_KEY")
        return None

    def check_password(self, input_password):
        CORRECT_PASSWORD = "beta" 
        return input_password == CORRECT_PASSWORD

    def get_model(self):
        try:
            for m in genai.list_models():
                if 'generateContent' in m.supported_generation_methods and 'flash' in m.name:
                    return m.name
            return 'models/gemini-1.5-flash'
        except:
            return 'models/gemini-1.5-flash'

    # --- UTILITIES ---
    
    def clean_markdown(self, text):
        """Removes Markdown symbols (*, #, etc) for clean PDF/Display."""
        # Remove bold/italic markers
        text = re.sub(r'\*\*(.*?)\*\*', r'\1', text) # Bold
        text = re.sub(r'\*(.*?)\*', r'\1', text)     # Italic
        text = re.sub(r'__(.*?)__', r'\1', text)     # Underline
        # Remove Headers
        text = re.sub(r'#+\s', '', text)
        return text

    def extract_text_from_pdf(self, uploaded_file):
        try:
            reader = PdfReader(uploaded_file)
            text = ""
            for page in reader.pages:
                text += page.extract_text()
            return text
        except Exception as e:
            return f"Error reading PDF: {e}"
            
    def extract_text_from_image(self, image):
        model_name = self.get_model()
        model = genai.GenerativeModel(model_name)
        prompt = "Transcribe all the text in this image exactly as written."
        try:
            response = model.generate_content([prompt, image])
            return response.text
        except:
            return ""

    def create_pdf(self, brand_name, rules_text):
        """Generates a clean, professional PDF without markdown artifacts."""
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Header
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, txt=f"Brand Guidelines: {brand_name}", ln=1, align='C')
        pdf.ln(5)
        
        # Clean the text
        clean_text = self.clean_markdown(rules_text)
        
        # Body
        pdf.set_font("Arial", size=11)
        # Handle unicode issues lightly by replacing common offenders
        clean_text = clean_text.replace("’", "'").replace("“", '"').replace("”", '"').replace("–", "-")
        
        pdf.multi_cell(0, 6, txt=clean_text)
        
        # Footer branding
        pdf.set_y(-15)
        pdf.set_font("Arial", 'I', 8)
        pdf.cell(0, 10, "Generated by Signet | Castellan PR", 0, 0, 'C')
        
        return pdf.output(dest='S').encode('latin-1')

    # --- AI TASKS ---

    def describe_logo(self, image):
        model_name = self.get_model()
        model = genai.GenerativeModel(model_name)
        prompt = "Describe this logo in technical detail for a Brand Guideline document. Focus on symbols, colors, layout, and vibe. Concise."
        try:
            response = model.generate_content([prompt, image])
            return response.text
        except Exception as e:
            return "Logo analysis failed."

    def run_visual_audit(self, image, rules):
        model_name = self.get_model()
        model = genai.GenerativeModel(model_name)
        prompt = f"""
        ### ROLE: Signet Compliance Engine.
        ### GUIDELINES:
        {rules}
        ### TASK: Audit the image.
        ### OUTPUT FORMAT:
        **COMPLIANCE SCORE:** [0-100]
        **STATUS:** [PASS / FAIL / WARNING]
        
        **1. VISUAL IDENTITY:** [Analysis]
        **2. TYPOGRAPHY:** [Analysis]
        **3. TONE & VIBE:** [Analysis]
        
        **REQUIRED FIXES:** [Bullets]
        """
        response = model.generate_content([prompt, image])
        return response.text

    def run_copy_editor(self, text, rules):
        model_name = self.get_model()
        model = genai.GenerativeModel(model_name)
        prompt = f"""
        ### ROLE: Senior Copy Editor.
        ### BRAND RULES:
        {rules}
        ### DRAFT:
        "{text}"
        ### OUTPUT:
        **1. CRITICAL EDITS:**
        **2. POLISHED COPY:**
        **3. STRATEGY NOTE:**
        """
        response = model.generate_content(prompt)
        return response.text

    def run_content_generator(self, topic, format_type, key_points, audience, rules, samples=[]):
        model_name = self.get_model()
        model = genai.GenerativeModel(model_name)
        
        relevant_samples = ""
        if samples:
            matches = [s['content'] for s in samples if s['type'].lower() in format_type.lower()]
            if not matches: matches = [s['content'] for s in samples]
            relevant_samples = "\n---\n".join(matches[:3])

        prompt = f"""
        ### ROLE: Executive Ghost Writer.
        ### BRAND RULES:
        {rules}
        ### REFERENCE VOICE SAMPLES:
        {relevant_samples}
        ### TASK: Write a {format_type} about "{topic}".
        ### AUDIENCE: {audience}
        ### KEY DETAILS:
        {key_points}
        """
        response = model.generate_content(prompt)
        return response.text
        
    def run_social_assistant(self, platform, topic, image, rules):
        model_name = self.get_model()
        model = genai.GenerativeModel(model_name)
        inputs = [f"""
        ### ROLE: Social Media Strategist.
        ### BRAND RULES:
        {rules}
        ### PLATFORM: {platform}
        ### TOPIC: {topic}
        
        ### TASK:
        1. Write a high-engagement caption.
        2. Provide strategic hashtags.
        3. EXPLAIN your choices.
        
        ### OUTPUT FORMAT:
        **CAPTION:** ...
        **HASHTAGS:** ...
        **STRATEGIC RATIONALE:** (Why this tone? Why these tags?)
        """]
        if image: inputs.append(image)
        response = model.generate_content(inputs)
        return response.text

    def generate_brand_rules(self, inputs):
        model_name = self.get_model()
        model = genai.GenerativeModel(model_name)
        response = model.generate_content(f"""
        ### ROLE: Brand Strategist.
        ### INPUTS: {inputs}
        ### INSTRUCTIONS:
        Create a clean, professional Brand Guideline.
        Avoid excessive markdown (bolding every word). Use clean headers.
        ### FORMAT:
           1. STRATEGY (Mission, Values, Archetype)
           2. COLOR PALETTE
           3. TYPOGRAPHY
           4. LOGO RULES
           5. VOICE & TONE (Style Signature)
        """)
        return response.text
